// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC_ZQ-chH241N1kkBc5YJuEj9TwnqRhKc',
    appId: '1:483135269546:android:3280ce73b0dcab626dbed3',
    messagingSenderId: '483135269546',
    projectId: 'hotelmanagament-c135c',
    databaseURL: 'https://hotelmanagament-c135c-default-rtdb.firebaseio.com',
    storageBucket: 'hotelmanagament-c135c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA-1rMWPGvfYzHRQwpHSSDRSOuIQCVcyQ',
    appId: '1:483135269546:ios:03b36cf949ea72276dbed3',
    messagingSenderId: '483135269546',
    projectId: 'hotelmanagament-c135c',
    databaseURL: 'https://hotelmanagament-c135c-default-rtdb.firebaseio.com',
    storageBucket: 'hotelmanagament-c135c.appspot.com',
    iosClientId: '483135269546-iccq64lub140d2s67gg3rnatkue59s1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestaodomiciliar',
  );
}
